# Введение в регрессионный анализ: интенсив по Python

*Алла Тамбовцева*

## Семинар 3. Описательные статистики в NumPy

### Немного теории: методы и функции для описательных статистик

In [1]:
import numpy as np

In [2]:
sample = np.array([20, 40, 60, 40, 45, 30, 
                   25, 25, 30, 40, 45, 50])

Методы:

In [3]:
print("Минимум:", sample.min())
print("Максимум:", sample.max())
print("Среднее:", sample.mean())

Минимум: 20
Максимум: 60
Среднее: 37.5


In [4]:
# смещенная оценка дисперсии (с делением на n)

print("Дисперсия:", sample.var())
print("Стандартное отклонение:", sample.std())

Дисперсия: 127.08333333333333
Стандартное отклонение: 11.273124382057235


In [5]:
# несмещенная оценка дисперсии (с делением на n-1)

print("Дисперсия:", sample.var(ddof=1))
print("Стандартное отклонение:", sample.std(ddof=1))

Дисперсия: 138.63636363636363
Стандартное отклонение: 11.77439440635329


Функции:

In [6]:
print(sample.median())

AttributeError: 'numpy.ndarray' object has no attribute 'median'

> Код выше не сработал, поскольку на массивах, действительно, не определен метод `.median()`. Однако есть функция с таким названием. То же самое с квантилями – только для их вычисления потребуется еще указать уровень в виде числа от 0 до 1. 

In [7]:
print(np.median(sample))
print(np.quantile(sample, 0.25)) # нижний квартиль
print(np.quantile(sample, 0.75)) # верхний квартиль

40.0
28.75
45.0


**Утешающий факт.** Если кажется, что в методах и функциях легко запутаться, для вычисления описательных статистик можно использовать функции и всегда писать их перед названием массива:

In [8]:
# всегда np. и название функции

print(np.min(sample))
print(np.max(sample))
print(np.mean(sample))
print(np.var(sample))
print(np.std(sample))

20
60
37.5
127.08333333333333
11.273124382057235


**Дополнительно.** В качестве аргумента в `.quantile()` можно указать не один уровень квантиля, а сразу несколько. Но тогда их нужно оформить в виде списка:

In [9]:
# квантиль уровня 0 – минимум, уровня 1 – максимум

print(np.quantile(sample, [0.25, 0.75])) 
print(np.quantile(sample, [0, 0.25, 0.75, 1]))

[28.75 45.  ]
[20.   28.75 45.   60.  ]


Если нужен перечень уровней с фиксированным шагом, можно воспользоваться функцией `np.arange()`. Например, для получения децилей выставим шаг 0.1:

In [10]:
# старт в 0, финиш в 1.1, шаг 0.1

print(np.arange(0, 1.1, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


Подставляем массив из уровней квантилей и получаем децили:

In [11]:
# нулевой дециль – это просто минимум 20
# десятый дециль – это просто максимум 60
# 10% значений не больше 25
# 20% значений не больше 26
# 30% значений не больше 30, итд

np.quantile(sample, np.arange(0, 1.1, 0.1))

array([20. , 25. , 26. , 30. , 34. , 40. , 40. , 43.5, 45. , 49.5, 60. ])

### Задача 1

В массиве `data` сохранена выборка.

* выберите нетипичные значения, сохраните их в массив `outliers` и посчитайте их количество
* оставьте в массиве `data` только типичные значения.

In [12]:
data = np.array([-0.3, -0.1, 0.5, -0.5, 1., 5.2, 10.6, 1.4, 1.,  
                 0., 0.3, 1.6, 1.4, -0.7, -0.2, 0.3, 0.5, 0.8,  
                 6.2, -2.4, 0.6, -1.9, -2.6, -1.6, -1.6, -0.,
                 -1.3, 0.7, -0., 1.3, 1., 0.1, 0.8, -1., 
                 -0.2, 4.5, 0., -0.7, -0.6, 0.6, 0.7, -0.5, 
                 -1.3, -0.8, 0., 0.4, -0.4, 0.6, 1.1, 0.9, 
                 -1.5, 0.4, -0.6, 1.1, -0.4, 1., -3.8, -0.9, 
                 -1.2, -1.9, -1.5, 1.2, 0.7, -3.6, 1.7, -1.1,
                 -0.3, -1.2, -0., 0.1, 0.6, 0.3, -0.3, -0.3, 
                 -0.4, -0.3, -0.8, 0.2, 0.8, -0.9, 1.1, 2.1, 
                 -1.2, 1.1, 0.3, 0.3, 0.4, -0.1, 0.4, 0.1, 
                 1.5, 0.4, 3.3, -0.3, 0.6, 0.7, -1.9, -1.5, 
                 -6.1, 0.4, 0.9, -0.5, -0.4, 0.1, 1.7, -0.8])

In [13]:
Q1 = np.quantile(data, 0.25)
Q3 = np.quantile(data, 0.75)
IR = Q3 - Q1
left = Q1 - 1.5 * IR
right = Q3 + 1.5 * IR

In [14]:
# нетипичные значения

outliers = data[(data < left) | (data > right)]
print(outliers)
print(len(outliers))

[ 5.2 10.6  6.2  4.5 -3.8 -3.6  3.3 -6.1]
8


In [15]:
# типичные значения
# выводим в отсортированном виде, 
# проверяем, что нетипичных не осталось

data = data[(data >= left) & (data <= right)]
print(sorted(data)) 

[np.float64(-2.6), np.float64(-2.4), np.float64(-1.9), np.float64(-1.9), np.float64(-1.9), np.float64(-1.6), np.float64(-1.6), np.float64(-1.5), np.float64(-1.5), np.float64(-1.5), np.float64(-1.3), np.float64(-1.3), np.float64(-1.2), np.float64(-1.2), np.float64(-1.2), np.float64(-1.1), np.float64(-1.0), np.float64(-0.9), np.float64(-0.9), np.float64(-0.8), np.float64(-0.8), np.float64(-0.8), np.float64(-0.7), np.float64(-0.7), np.float64(-0.6), np.float64(-0.6), np.float64(-0.5), np.float64(-0.5), np.float64(-0.5), np.float64(-0.4), np.float64(-0.4), np.float64(-0.4), np.float64(-0.4), np.float64(-0.3), np.float64(-0.3), np.float64(-0.3), np.float64(-0.3), np.float64(-0.3), np.float64(-0.3), np.float64(-0.2), np.float64(-0.2), np.float64(-0.1), np.float64(-0.1), np.float64(0.0), np.float64(-0.0), np.float64(-0.0), np.float64(0.0), np.float64(0.0), np.float64(-0.0), np.float64(0.1), np.float64(0.1), np.float64(0.1), np.float64(0.1), np.float64(0.2), np.float64(0.3), np.float64(0.3), n

### Задача 2

Проверьте, есть ли в выборке `data` нетипичные значения, считая, что нетипичные значения – те, которые отклоняются от выборочного среднего более, чем на два стандартных отклонения.

In [16]:
# вернем data в исходный вид
# скопируем из задачи 1

data = np.array([-0.3, -0.1, 0.5, -0.5, 1., 5.2, 10.6, 1.4, 1.,  
                 0., 0.3, 1.6, 1.4, -0.7, -0.2, 0.3, 0.5, 0.8,  
                 6.2, -2.4, 0.6, -1.9, -2.6, -1.6, -1.6, -0.,
                 -1.3, 0.7, -0., 1.3, 1., 0.1, 0.8, -1., 
                 -0.2, 4.5, 0., -0.7, -0.6, 0.6, 0.7, -0.5, 
                 -1.3, -0.8, 0., 0.4, -0.4, 0.6, 1.1, 0.9, 
                 -1.5, 0.4, -0.6, 1.1, -0.4, 1., -3.8, -0.9, 
                 -1.2, -1.9, -1.5, 1.2, 0.7, -3.6, 1.7, -1.1,
                 -0.3, -1.2, -0., 0.1, 0.6, 0.3, -0.3, -0.3, 
                 -0.4, -0.3, -0.8, 0.2, 0.8, -0.9, 1.1, 2.1, 
                 -1.2, 1.1, 0.3, 0.3, 0.4, -0.1, 0.4, 0.1, 
                 1.5, 0.4, 3.3, -0.3, 0.6, 0.7, -1.9, -1.5, 
                 -6.1, 0.4, 0.9, -0.5, -0.4, 0.1, 1.7, -0.8])

In [17]:
a = data.mean()
s = data.std()

lower = a - 2 * s
upper = a + 2 * s

out = data[(data < lower) | (data > upper)]
print(out)
print(len(out))

[ 5.2 10.6  6.2  4.5 -3.8 -3.6 -6.1]
7


> И в первой задаче, и во второй задаче мы ищем нетипичные значения, просто по разным критериям (1.5×IR против 2×STD). Результаты могут немного отличаться, по второму критерию нетипичных значений на одно меньше, значение 3.3 не было «признано» нетипичным.

### Задача 3

В выборке `income` сохранены значения заработной платы сотрудников. Вычислите децильный коэффициент для оценки неравенства доходов, который получается делением среднего дохода самых 10% богатых на средний доход 10% самых бедных.

In [18]:
income = np.array([ 70000,  90000,  61000,  60000, 150000, 155000, 160000, 162000,
       156000, 130000, 137000,  45000,  48000,  51000,  49500,  53000,
        65000,  63000,  64000,  80000,  82000,  58000])

In [19]:
# 10% самых богатых – значения выше 9-го дециля
# 10% самых бедных – значения ниже 1-го дециля

rich = income[income > np.quantile(income, 0.9)]
poor = income[income < np.quantile(income, 0.1)]
print(rich)
print(poor)

[160000 162000 156000]
[45000 48000 49500]


In [20]:
# считаем средние по rich и poor, затем коэффициент
coef = rich.mean() / poor.mean()
print(coef)

3.354385964912281
