# Введение в регрессионный анализ: интенсив по Python

*Алла Тамбовцева*

## Семинар 2. Работа с массивами NumPy: часть 2

### Немного теории: объединение условий

In [1]:
import numpy as np

sample = np.array([5, 10, 7, 45, 32, 12, 19, 17, 19, 10, 24, 30, 3])

In [2]:
# оператор И (and)
# одновременное выполнение условий – оба верны
# выбираем элементы более 10 и не более 30

chosen_one = sample[(sample > 10) & (sample <= 30)]
print(chosen_one)

[12 19 17 19 24 30]


In [3]:
# оператор ИЛИ (or)
# верно хотя бы одно условие: либо первое, либо второе, либо оба,
# выбираем четные элементы или кратные 3

chosen_two = sample[(sample % 2 == 0) | (sample % 3 == 0)]
print(chosen_two)

[10 45 32 12 10 24 30  3]


> Оператор `%` вычисляет остаток от деления на число. Например, код `56 % 7` вернет число 0, так как 56 делится на 7 без остатка, а код `56 % 3` вернет число 2, так как остаток от деления 56 на 3 равен 2 (на 3 нацело делится 54, а до 56 остается 2). Здесь мы проверяем условие равенства остатка 0, так как четные числа – те, что делятся на 2 без остатка, а кратные 3 – те, что делятся на 3 без остатка).

In [4]:
# оператор ИСКЛЮЧАЮЩЕЕ ИЛИ
# верно ровно одно условие: либо только первое, либо только второе
# выбираем четные элементы или кратные 3, исключая те, что делятся и на 2 и на 3 сразу,
# по сравнению с предыдущим результатом выкинули 12, 24, 30

chosen_two = sample[(sample % 2 == 0) ^ (sample % 3 == 0)]
print(chosen_two)

[10 45 32 10  3]


### Задача 1. Осенняя

Ежегодно осенью в «Аптекарском огороде» (Ботанический сад МГУ) проводится выставка больших тыкв. В массиве `pumpkins` сохранена выборка значений веса таких тыкв в разные годы.

In [5]:
pumpkins = np.array([547, 566.5, 522, 130, 169, 384, 501, 531, 300, 
                     267, 105, 202, 446, 430, 548, 692.5, 645.5, 401])

a. Известно, что тыква считается гигантской, если ее вес составляет не менее 200 кг. Выберите из массива `pumpkins` соответствующие значения и сохраните их в массив `giants`. Вычислите число гигантских тыкв.

b. Выберите из массива `pumpkins` четные значения и сохраните их в массив `even`.

c. Выберите из массива `pumpkins` значения более 600 или менее 250 и сохраните их в массив `non_typical`.

d. Выберите из массива `pumpkins` четные значения не больше 300 и выведите их на экран.

In [6]:
# a
giants = pumpkins[pumpkins >= 200]
print(len(giants))

15


In [7]:
# b
even = pumpkins[pumpkins % 2 == 0]
print(even)

[522. 130. 384. 300. 202. 446. 430. 548.]


In [8]:
# c
non_typical = pumpkins[(pumpkins > 600) | (pumpkins < 250)]
print(non_typical)

[130.  169.  105.  202.  692.5 645.5]


In [9]:
# d
print(pumpkins[(pumpkins % 2 == 0) & (pumpkins <= 300)])

[130. 300. 202.]


### Задача 2. Экспериментальная

В массиве `group` зафиксировано, к какой группе относится участник эксперимента, посвященного эффективности медицинского препарата. Группы A и B являются тестовыми – участники принимают препарат в разных дозировках, а группа C является контрольной – участники принимают плацебо.

In [10]:
group = np.array(["A", "A", "A", "B", "C", "A", "B", "B", "B", "B", 
                  "C", "A", "A", "C", "C", "C", "A", "B", "B", "A", 
                  "A", "A", "B", "B", "B", "C", "A", "A", "B", "C",
                  "B", "C", "A", "B", "A", "C", "B", "B", "C", "B", 
                  "B", "C", "A", "C", "C", "A", "A", "C", "B", "A"])

Выберите из массива `group` представителей групп A и B и сохраните их в массив `test`, остальных сохраните в массив `control`.

In [11]:
test = group[(group == "A") | (group == "B")]
print(test)

['A' 'A' 'A' 'B' 'A' 'B' 'B' 'B' 'B' 'A' 'A' 'A' 'B' 'B' 'A' 'A' 'A' 'B'
 'B' 'B' 'A' 'A' 'B' 'B' 'A' 'B' 'A' 'B' 'B' 'B' 'B' 'A' 'A' 'A' 'B' 'A']


In [12]:
control = group[group == "C"]
print(control)

['C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C']


In [13]:
# как вариант, раз кроме A, B, C значений нет,
# можно test получить просто отрицанием C

test = group[(group != "C")]
print(test)

['A' 'A' 'A' 'B' 'A' 'B' 'B' 'B' 'B' 'A' 'A' 'A' 'B' 'B' 'A' 'A' 'A' 'B'
 'B' 'B' 'A' 'A' 'B' 'B' 'A' 'B' 'A' 'B' 'B' 'B' 'B' 'A' 'A' 'A' 'B' 'A']


### Задача 3. Заморская

В массиве `scores` сохранены значения итогового [индекса](https://www.charitynavigator.org/about-us/our-methodology/ratings/#accordion-0f1da9ef58-item-0e8e991d85) качества работы НКО для организаций штата Мэриленд.

In [14]:
scores = np.array([85.59, 85.81, 90.75, 90.04, 85.85, 81.58, 81.86,  
                  84.98, 60.29, 81.65, 98.23, 97.17, 96.66, 90.97,  
                  88.93, 90.20, 77.26, 82.30, 94.69, 90.94, 80.33, 
                  80.56, 75.80, 95.12, 82.58, 84.20, 82.13, 90.13,  
                  95.70, 87.58, 95.11, 89.48, 76.03, 83.95, 76.07,  
                  94.81, 82.26, 90.81, 50.19, 92.02, 78.86, 80.87,  
                  75.18, 87.87, 85.15, 93.31, 91.85, 83.08, 92.48,  
                  91.26, 86.15, 87.54, 79.87, 88.79, 87.39, 90.71,
                  85.34, 90.00, 83.56, 89.88, 95.00, 84.78, 87.77,  
                  85.43, 96.16, 82.79, 94.74, 86.07, 94.18, 90.31,  
                  89.87, 82.18, 70.41, 83.55, 88.53, 89.02, 91.57,  
                  86.10, 76.25, 28.86, 91.20, 91.36, 80.68, 93.31,  
                  92.22, 86.21, 75.84, 90.15, 82.37, 77.23, 100.0,  
                  97.17, 91.51, 78.71, 83.65, 90.58, 77.15, 73.76,  
                  93.98, 91.36, 88.57, 88.18, 79.90, 82.58, 79.84,  
                  86.20, 85.93, 96.17, 89.09, 88.05, 74.78, 89.35,
                  94.88, 90.71, 92.74, 80.71, 87.35, 85.88, 90.54,  
                  75.88, 87.25, 86.35, 85.81, 97.13, 91.29, 97.23,  
                  94.91, 96.74, 86.65, 79.24, 97.17, 87.17, 83.76,  
                  90.00, 90.45, 29.25, 89.44, 83.40, 90.22, 79.19,  
                  94.66, 76.31, 90.27, 92.92, 91.61, 82.11, 96.20,  
                  80.34, 99.83, 84.63, 67.46, 92.41, 92.38, 85.57,  
                  92.24, 88.56, 76.67, 80.81, 91.94, 83.22, 83.62,  
                  97.17, 70.94, 89.18, 84.66, 80.55, 82.93])

a. Сохраните в массив `top` значения индекса выше 90.

b. Сохраните в массив `good` значения индекса от 75 до 89 включительно.

c. Сохраните в массив `scores_out` нехарактерные значения индекса, если известно, что границы характерных значений выглядят следующим образом: [68.51, 105.07].

d. Проверьте, есть ли в массиве `scores` значения, которые отклоняются от среднего более, чем на два стандартных отклонения (среднее – метод `.mean()`, стандартное отклонение – метод `.std()`). Если такие значения есть, найдите их количество.

In [15]:
### YOUR CODE HERE ###

# обсудим на семинаре 3